CREATE TABLE [dbo].[TaskTracks]
(
	[TaskTrackId] INT NOT NULL IDENTITY,
	[UserTaskId] INT NOT NULL,
	[TrackDate] DATE NOT NULL,
	[TrackNote] NVARCHAR(250) NULL

	CONSTRAINT PK_TaskTrackId PRIMARY KEY (TaskTrackId),
	CONSTRAINT FK_UserTaskId FOREIGN KEY (UserTaskId) REFERENCES UserTasks(UserTaskId) ON UPDATE CASCADE ON DELETE CASCADE
)
